#:schema node_modules/wrangler/config-schema.json
name = "dinyuezhuanhuan-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "16cd5bcfa7514ac5aa32ac342702d461" }
]

[assets]
directory = "./public"
